### ISSUE TITLE
Only default to 5xx errors

### ISSUE THREAD

**Issue by bumi** [getAlby/nginx-default-backend#2]
Apps (like the rails app) use HTTP 4xx status codes intentionally and use them to communicate to clients (e.g. when doing API calls or calls from JS) 

I think we should only overwrite 5xx errors which are unexpected server errors

**Comment by kiwiidb** [comment]
I think this is already the case. This is done with config at runtime:
https://github.com/getAlby/alby-deployment/commit/907880c01aa6400e034ed6a3db2b96703533a4f6

**Comment by bumi** [comment]
ahh 👍
